project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "blog/**/*.qmd"
    - "!index.Rmd"
    - "!packages.Rmd"
    - "!dev/*"
    - "!*.md"
    - "!README*"
    - "!QUARTO*"
    - "!*-old.qmd"
  resources:
    - "images/"

execute:
  freeze: auto

website:
  title: "Michael Friendly"
  description: "Data Visualization Research, R Packages, and Teaching"
  favicon: images/MF-face.png

  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        icon: house
        href: index.qmd
      - text: "R Packages"
        icon: box-seam
        href: packages.qmd
      - text: "Books"
        icon: book
        href: books.qmd
      - text: "Courses"
        icon: mortarboard
        href: courses.qmd
      - text: "Other Software"
        icon: code-slash
        href: software.qmd
      - text: "Blog"
        icon: pencil
        href: blog/index.qmd
    right:
      - icon: github
        href: https://github.com/friendly
        aria-label: GitHub
      - text: <img src="images/bluesky-logo.png" style="height:1.2em; vertical-align:middle;">
        href: https://bsky.app/profile/datavisfriendly.bsky.social
        aria-label: BlueSky

  page-footer:
    left: "Copyright 2025, Michael Friendly"
    right:
      - text: "friendly.github.io/"
        href: https://friendly.github.io/

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
    page-layout: full
