<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Michael Friendly">
<meta name="dcterms.date" content="2026-07-09">
<meta name="description" content="Exploring an exact combinatorial result and Monte Carlo approximation for determinants of all permutation matrices of the digits 1–9">

<title>Distribution of Determinants of 3×3 Matrices from {1,2,…,9}</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<meta name="quarto:status" content="draft">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light"><div id="quarto-draft-alert" class="alert alert-warning"><i class="bi bi-pencil-square"></i>Draft</div>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#exact-solution-all-9-permutations" id="toc-exact-solution-all-9-permutations" class="nav-link" data-scroll-target="#exact-solution-all-9-permutations">Exact Solution: All 9! Permutations</a></li>
  <li><a href="#random-permutation-distribution" id="toc-random-permutation-distribution" class="nav-link" data-scroll-target="#random-permutation-distribution">Random Permutation Distribution</a></li>
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics">Summary Statistics</a></li>
  <li><a href="#visualizations" id="toc-visualizations" class="nav-link" data-scroll-target="#visualizations">Visualizations</a>
  <ul class="collapse">
  <li><a href="#comparison-of-both-methods" id="toc-comparison-of-both-methods" class="nav-link" data-scroll-target="#comparison-of-both-methods">Comparison of Both Methods</a></li>
  <li><a href="#exact-distribution-detailed-view" id="toc-exact-distribution-detailed-view" class="nav-link" data-scroll-target="#exact-distribution-detailed-view">Exact Distribution (Detailed View)</a></li>
  </ul></li>
  <li><a href="#additional-analysis" id="toc-additional-analysis" class="nav-link" data-scroll-target="#additional-analysis">Additional Analysis</a>
  <ul class="collapse">
  <li><a href="#quartiles" id="toc-quartiles" class="nav-link" data-scroll-target="#quartiles">Quartiles</a></li>
  <li><a href="#skewness" id="toc-skewness" class="nav-link" data-scroll-target="#skewness">Skewness</a></li>
  <li><a href="#most-common-values" id="toc-most-common-values" class="nav-link" data-scroll-target="#most-common-values">Most Common Values</a></li>
  </ul></li>
  <li><a href="#why-this-shape-an-analytical-perspective" id="toc-why-this-shape-an-analytical-perspective" class="nav-link" data-scroll-target="#why-this-shape-an-analytical-perspective">Why this shape? An analytical perspective</a>
  <ul class="collapse">
  <li><a href="#why-symmetric" id="toc-why-symmetric" class="nav-link" data-scroll-target="#why-symmetric">Why symmetric?</a></li>
  <li><a href="#why-tent-shaped" id="toc-why-tent-shaped" class="nav-link" data-scroll-target="#why-tent-shaped">Why tent-shaped?</a></li>
  <li><a href="#an-exact-analytic-formula" id="toc-an-exact-analytic-formula" class="nav-link" data-scroll-target="#an-exact-analytic-formula">An exact analytic formula?</a></li>
  </ul></li>
  <li><a href="#extending-to-other-sizes" id="toc-extending-to-other-sizes" class="nav-link" data-scroll-target="#extending-to-other-sizes">Extending to Other Sizes</a>
  <ul class="collapse">
  <li><a href="#the-22-baseline" id="toc-the-22-baseline" class="nav-link" data-scroll-target="#the-22-baseline">The 2×2 baseline</a></li>
  <li><a href="#when-enumeration-isnt-an-option" id="toc-when-enumeration-isnt-an-option" class="nav-link" data-scroll-target="#when-enumeration-isnt-an-option">4×4: When Enumeration Isn’t an Option</a></li>
  <li><a href="#monte-carlo-approximation-of-the-shape" id="toc-monte-carlo-approximation-of-the-shape" class="nav-link" data-scroll-target="#monte-carlo-approximation-of-the-shape">Monte Carlo approximation of the shape</a></li>
  <li><a href="#a-surprise-more-terms-but-less-gaussian" id="toc-a-surprise-more-terms-but-less-gaussian" class="nav-link" data-scroll-target="#a-surprise-more-terms-but-less-gaussian">A surprise: more terms, but <em>less</em> Gaussian</a></li>
  <li><a href="#finding-the-true-extremes-sampling-isnt-enough" id="toc-finding-the-true-extremes-sampling-isnt-enough" class="nav-link" data-scroll-target="#finding-the-true-extremes-sampling-isnt-enough">Finding the true extremes: sampling isn’t enough</a></li>
  <li><a href="#uncharted-territory" id="toc-uncharted-territory" class="nav-link" data-scroll-target="#uncharted-territory">Uncharted territory?</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Distribution of Determinants of 3×3 Matrices from {1,2,…,9}</h1>
  <div class="quarto-categories">
    <div class="quarto-category">R</div>
    <div class="quarto-category">combinatorics</div>
    <div class="quarto-category">linear algebra</div>
    <div class="quarto-category">simulation</div>
  </div>
  </div>

<div>
  <div class="description">
    Exploring an exact combinatorial result and Monte Carlo approximation for determinants of all permutation matrices of the digits 1–9
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Michael Friendly </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 9, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">July 20, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<!--
DRAFT: this is the published 3x3 post (blog/posts/2026-07-determinant-distributions/index.qmd)
with a new "Extending to 4x4" section added before the Conclusions. Everything down through
"An exact analytic formula?" is unchanged from the published version. Needs review before merging
back into the published post -- in particular the Conclusions section still only talks about 3x3
and should be revised to reflect the 4x4 material.
-->
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>From the time, long ago, I first studied linear algebra, I’ve always had a fascination with the idea of the determinant of a square matrix, <span class="math inline">\(\text{det}(\mathbf{A}) \equiv | \mathbf{A} |\)</span>. You just take your matrix <span class="math inline">\(\mathbf{A}\)</span>, which could be <span class="math inline">\((2 \times 2)\)</span>, or <span class="math inline">\((10 \times 10)\)</span>, or <span class="math inline">\((100 \times 100)\)</span>, … and <span class="math inline">\(| \mathbf{A} |\)</span> turns that into a <em>single number</em>, that expresses many of its properties—algebraic, geometric and statistical.</p>
<p>In short, the determinant <span class="math inline">\(| \mathbf{A} |\)</span> is a measure of the “size” of <span class="math inline">\(\mathbf{A}\)</span>. So, when we’re talking about the covariance matrix <span class="math inline">\(\mathbf{S}\)</span> of data variables, <span class="math inline">\(| \mathbf{S} |\)</span> is a measure of total variance, taking correlations into account.</p>
<p>The concept has a surprisingly long history. Traces appear in ancient Chinese mathematics — the <em>Nine Chapters on the Mathematical Art</em> (~200 BC) solved systems of equations using what amounts to determinant-like elimination — and independent discoveries by Seki Takakazu in Japan (1683) and Leibniz (1693) formalized the idea in the West. The word “determinant” itself came from Cauchy in 1812, who also standardized much of the modern notation; Cayley’s 1858 paper on matrix algebra finally set it in the broader context of linear transformations. For a full account, the <a href="https://mathshistory.st-andrews.ac.uk/HistTopics/Matrices_and_determinants/">MacTutor history</a> is the place to start.</p>
<p>This post explores an interesting combinatorial and statistical problem:</p>
<blockquote class="blockquote">
<p>What is the distribution of determinants of all 3×3 matrices that can be formed from the numbers 1 through 9, each used exactly once?</p>
</blockquote>
<p>It arose from a simpler question Math StackExchange: What is the <a href="https://math.stackexchange.com/questions/2339056/total-number-of-3x3-matrices-using-only-digits-1-to-9">total number 3x3 matrices using only digits 1 to 9?</a></p>
<p>We answer this question in two ways:</p>
<ol type="1">
<li><strong>Exact solution</strong>: Calculate the determinant for all 9! = 362,880 permutations</li>
<li><strong>Permutation distribution</strong>: Generate a large number of random permutations and approximate the distribution</li>
</ol>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>Load the packages we’ll use here.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arrangements)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="exact-solution-all-9-permutations" class="level2">
<h2 class="anchored" data-anchor-id="exact-solution-all-9-permutations">Exact Solution: All 9! Permutations</h2>
<p><span class="math inline">\(9! = 362,880\)</span> is a large number, but not so large to preclude an elegant two-line computational solution, even if it takes time and storage space.</p>
<ul>
<li>Use <code>arrangements::permutations()</code> to generate all of these</li>
<li>Use <code>apply()</code> to calculate their determinants, with a helper function <code>det_from_vec()</code></li>
</ul>
<p>Computing exact distribution using all 362,880 permutations of the digits 1-9.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>det_from_vec <span class="ot">&lt;-</span> <span class="cf">function</span>(v) {</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  M <span class="ot">&lt;-</span> <span class="fu">matrix</span>(v, <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">det</span>(M)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>all_perms <span class="ot">&lt;-</span> arrangements<span class="sc">::</span><span class="fu">permutations</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">k =</span> <span class="dv">9</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>determinants_exact <span class="ot">&lt;-</span> <span class="fu">apply</span>(all_perms, <span class="dv">1</span>, det_from_vec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="random-permutation-distribution" class="level2">
<h2 class="anchored" data-anchor-id="random-permutation-distribution">Random Permutation Distribution</h2>
<p>Generating a Monte Carlo approximation with a large random sample of permutations. Here, <code>replicate()</code> is used to repeatedly apply the function <code>det_from_vec()</code> on a random permutation.</p>
<p>As you can see, they are very nearly identical.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">100000</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>determinants_random <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, {</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="dv">9</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">det_from_vec</span>(v)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="summary-statistics" class="level2">
<h2 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h2>
<p>How do the exact and simulated distributions compare?</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>det_summary <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">N       =</span> <span class="fu">length</span>(x),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Min     =</span> <span class="fu">min</span>(x),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Max     =</span> <span class="fu">max</span>(x),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean    =</span> <span class="fu">round</span>(<span class="fu">mean</span>(x), <span class="dv">2</span>),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Median  =</span> <span class="fu">median</span>(x),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">SD      =</span> <span class="fu">round</span>(<span class="fu">sd</span>(x), <span class="dv">2</span>),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Unique  =</span> <span class="fu">length</span>(<span class="fu">unique</span>(x)),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Zero %</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">mean</span>(x <span class="sc">==</span> <span class="dv">0</span>), <span class="dv">2</span>),</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(<span class="at">Method =</span> <span class="st">"Exact (9! permutations)"</span>,           <span class="fu">det_summary</span>(determinants_exact)),</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cbind</span>(<span class="at">Method =</span> <span class="fu">paste0</span>(<span class="st">"Random sample (B = "</span>, <span class="fu">format</span>(B, <span class="at">big.mark=</span><span class="st">","</span>), <span class="st">")"</span>), <span class="fu">det_summary</span>(determinants_random))</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                       Method      N  Min Max Mean Median     SD Unique Zero %
1     Exact (9! permutations) 362880 -412 412 0.00      0 154.85   3891   0.41
2 Random sample (B = 100,000) 100000 -412 412 0.05      0 155.43   3451   0.40</code></pre>
</div>
</div>
</section>
<section id="visualizations" class="level2">
<h2 class="anchored" data-anchor-id="visualizations">Visualizations</h2>
<section id="comparison-of-both-methods" class="level3">
<h3 class="anchored" data-anchor-id="comparison-of-both-methods">Comparison of Both Methods</h3>
<p>We can compare the distributions by overlaying them in a single plot, showing the exact and permutation distributions as both histograms and density curves.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df_combined <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">determinant =</span> determinants_exact,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">method =</span> <span class="st">"Exact (all 9! permutations)"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">determinant =</span> determinants_random,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">method =</span> <span class="fu">paste0</span>(<span class="st">"Random sample (B = "</span>, <span class="fu">format</span>(B, <span class="at">big.mark =</span> <span class="st">","</span>), <span class="st">")"</span>))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_combined, <span class="fu">aes</span>(<span class="at">x =</span> determinant, <span class="at">fill =</span> method)) <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">100</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color =</span> method), <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#3498db"</span>, <span class="st">"#e74c3c"</span>)) <span class="sc">+</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#2c3e50"</span>, <span class="st">"#c0392b"</span>)) <span class="sc">+</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribution of Determinants of 3×3 Matrices from {1,2,...,9}"</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Each matrix uses digits 1-9 exactly once"</span>,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Determinant"</span>, <span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">fill =</span> <span class="st">"Method"</span>, <span class="at">color =</span> <span class="st">"Method"</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/plot-comparison-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exact-distribution-detailed-view" class="level3">
<h3 class="anchored" data-anchor-id="exact-distribution-detailed-view">Exact Distribution (Detailed View)</h3>
<p>The exact distribution has an interesting shape. It is symmetric around 0; the density plot shows a bunch of small “shoulders”, and there are lots of spikes and troughs.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">determinant =</span> determinants_exact), <span class="fu">aes</span>(<span class="at">x =</span> determinant)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">120</span>, <span class="at">fill =</span> <span class="st">"#3498db"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"#2c3e50"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Exact Distribution: All 362,880 Permutations"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Determinants of 3×3 matrices using digits 1-9 once each"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Determinant"</span>, <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/plot-exact-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="additional-analysis" class="level2">
<h2 class="anchored" data-anchor-id="additional-analysis">Additional Analysis</h2>
<p>The mathematical form of this distribution is unknown, so to supplement the eye-ball view above, some summary statistics help characterize it more precisely. Because the distribution is exactly symmetric around zero (as the analytical argument confirms), the mean and median are both zero and skewness measures vanish; the interesting quantities are those that capture spread and shape.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean   =</span> <span class="fu">mean</span>(determinants_exact),</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">median =</span> <span class="fu">median</span>(determinants_exact),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd     =</span> <span class="fu">round</span>(<span class="fu">sd</span>(determinants_exact), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                        mean                       median 
 -0.000000000000000002021716   0.000000000000000000000000 
                          sd 
154.853000000000008640199667 </code></pre>
</div>
</div>
<section id="quartiles" class="level3">
<h3 class="anchored" data-anchor-id="quartiles">Quartiles</h3>
<p>Because the distribution is exactly symmetric, Q1 = −Q3 and the median is 0. The interquartile range (Q3 − Q1) covers the middle 50% of determinant values, and the min/max give the full support of the distribution.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(determinants_exact, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  0%  25%  50%  75% 100% 
-412 -101    0  101  412 </code></pre>
</div>
</div>
</section>
<section id="skewness" class="level3">
<h3 class="anchored" data-anchor-id="skewness">Skewness</h3>
<p>With exact symmetry guaranteed analytically, both the parametric skewness (third standardized central moment, via <code>skewness()</code> from <code>moments</code>) and the non-parametric <a href="https://en.wikipedia.org/wiki/Skewness#Quartile-based_measures">Bowley quartile skewness</a>, <span class="math inline">\((Q_3 + Q_1 - 2Q_2)/(Q_3 - Q_1)\)</span>, should be exactly zero:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">quantile</span>(determinants_exact, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">parametric =</span> <span class="fu">skewness</span>(determinants_exact),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">bowley     =</span> <span class="fu">unname</span>((q[<span class="dv">3</span>] <span class="sc">+</span> q[<span class="dv">1</span>] <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> q[<span class="dv">2</span>]) <span class="sc">/</span> (q[<span class="dv">3</span>] <span class="sc">-</span> q[<span class="dv">1</span>])))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                  parametric                       bowley 
0.00000000000000000001157529 0.00000000000000000000000000 </code></pre>
</div>
</div>
<p>Both are effectively zero, as expected: for every permutation yielding determinant <span class="math inline">\(d\)</span>, swapping any two rows produces determinant <span class="math inline">\(-d\)</span>, giving an exact bijection between the positive and negative halves of the distribution.</p>
</section>
<section id="most-common-values" class="level3">
<h3 class="anchored" data-anchor-id="most-common-values">Most Common Values</h3>
<p>Because the distribution is discrete and integer-valued, some determinant values occur far more often than others. The ten most frequent values are:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(determinants_exact), <span class="at">decreasing =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>determinants_exact
 -45   45  -27   27  -55   55  -65  -11   11   65 
1704 1704 1611 1611 1503 1503 1500 1500 1500 1500 </code></pre>
</div>
</div>
<p>Each positive value in this table is matched exactly by its negative counterpart, again confirming symmetry. This table of modal values has a direct analogue in the 4×4 case below, though there it must be estimated from a Monte Carlo sample rather than computed exactly — making this 3×3 baseline a useful point of comparison.</p>
</section>
</section>
<section id="why-this-shape-an-analytical-perspective" class="level2">
<h2 class="anchored" data-anchor-id="why-this-shape-an-analytical-perspective">Why this shape? An analytical perspective</h2>
<p>The two most striking features of the distribution—perfect symmetry around zero and the tent-like (near-triangular) shape—both have mathematical explanations rooted in the structure of the determinant.</p>
<section id="why-symmetric" class="level3">
<h3 class="anchored" data-anchor-id="why-symmetric">Why symmetric?</h3>
<p>For any filling of the 3×3 matrix with a permutation of <span class="math inline">\(\{1, \ldots, 9\}\)</span> that yields <span class="math inline">\(\det(\mathbf{A}) = d\)</span>, swapping any two rows produces another valid filling (still a permutation of <span class="math inline">\(\{1, \ldots, 9\}\)</span>) with <span class="math inline">\(\det = -d\)</span>. This gives an exact bijection between fillings with determinant <span class="math inline">\(d\)</span> and fillings with determinant <span class="math inline">\(-d\)</span>, so the distribution is perfectly symmetric around zero—not approximately, but exactly.</p>
</section>
<section id="why-tent-shaped" class="level3">
<h3 class="anchored" data-anchor-id="why-tent-shaped">Why tent-shaped?</h3>
<p>The <a href="https://en.wikipedia.org/wiki/Leibniz_formula_for_determinants">Leibniz formula</a> expands the 3×3 determinant into exactly six signed products, three positive and three negative:</p>
<p><span class="math display">\[
\det(\mathbf{A}) = \underbrace{(a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32})}_{P}
                 - \underbrace{(a_{13}a_{22}a_{31} + a_{11}a_{23}a_{32} + a_{12}a_{21}a_{33})}_{N}
\]</span></p>
<p>Each of <span class="math inline">\(P\)</span> and <span class="math inline">\(N\)</span> is a sum of three products, one from each row and each column—a “Latin square transversal” of the matrix. By the same even/odd permutation symmetry, <span class="math inline">\(P\)</span> and <span class="math inline">\(N\)</span> have identical marginal distributions, so <span class="math inline">\(\det = P - N\)</span> is symmetric.</p>
<p>The <strong>shape</strong> of <span class="math inline">\(P - N\)</span> depends on how close to uniform the marginal distribution of <span class="math inline">\(P\)</span> (or <span class="math inline">\(N\)</span>) is. If <span class="math inline">\(P\)</span> were exactly uniform on some interval <span class="math inline">\([a, b]\)</span>, the difference of two independent copies would be exactly triangular (the <a href="https://en.wikipedia.org/wiki/Irwin%E2%80%93Hall_distribution">Irwin–Hall</a> <span class="math inline">\(n=2\)</span> case). <span class="math inline">\(P\)</span> and <span class="math inline">\(N\)</span> aren’t independent—they share the same nine entries—but their marginal distributions are bounded, roughly unimodal, and symmetric enough that the difference is close to triangular rather than Gaussian.</p>
<p>The distribution never approaches Gaussian here because:</p>
<ul>
<li>The <strong>support is bounded</strong>: determinant values are constrained to a finite range.</li>
<li>Only <strong>six terms</strong> contribute; the Central Limit Theorem requires many independent summands.</li>
<li>The terms are <strong>not independent</strong>: entries of <span class="math inline">\(\mathbf{A}\)</span> are a permutation, so all nine values constrain each other.</li>
</ul>
</section>
<section id="an-exact-analytic-formula" class="level3">
<h3 class="anchored" data-anchor-id="an-exact-analytic-formula">An exact analytic formula?</h3>
<p>The exact distribution computed above is a discrete distribution on integer values. But is there a closed-form expression for it — a formula that gives, for each integer <span class="math inline">\(d\)</span>, exactly how many of the 9! permutations produce <span class="math inline">\(\text{det}(\mathbf{A}) = d\)</span>?</p>
<p>The short answer is: if there is, not a simple one. The problem is equivalent to counting integer solutions to the determinant expansion</p>
<p><span class="math display">\[a_{11}(a_{22}a_{33} - a_{23}a_{32}) - a_{12}(a_{21}a_{33} - a_{23}a_{31}) + a_{13}(a_{21}a_{32} - a_{22}a_{31}) = d\]</span></p>
<p>subject to the constraint that <span class="math inline">\((a_{11}, \ldots, a_{33})\)</span> is a permutation of <span class="math inline">\(\{1, \ldots, 9\}\)</span>. This is a system of Diophantine equations with a permutation constraint, and no general closed form is known. The brute-force enumeration we performed is, in a sense, the answer — the distribution <em>is</em> the count table. One could express it via a generating function or characteristic function, but these don’t simplify to anything more illuminating than the enumeration itself. The problem is harder than it looks.</p>
</section>
</section>
<section id="extending-to-other-sizes" class="level2">
<h2 class="anchored" data-anchor-id="extending-to-other-sizes">Extending to Other Sizes</h2>
<section id="the-22-baseline" class="level3">
<h3 class="anchored" data-anchor-id="the-22-baseline">The 2×2 baseline</h3>
<p>Before pushing to 4×4, it is worth glancing back at the smaller case: 2×2 matrices built from the digits 1–4, each used once. There are only <span class="math inline">\(4! = 24\)</span> permutations, so exact enumeration is trivial.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>all_perms_2x2 <span class="ot">&lt;-</span> arrangements<span class="sc">::</span><span class="fu">permutations</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">k =</span> <span class="dv">4</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>dets_2x2 <span class="ot">&lt;-</span> <span class="fu">apply</span>(all_perms_2x2, <span class="dv">1</span>,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                  <span class="cf">function</span>(v) <span class="fu">det</span>(<span class="fu">matrix</span>(v, <span class="dv">2</span>, <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(dets_2x2))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>dets_2x2
-10  -5  -2   2   5  10 
  4   4   4   4   4   4 </code></pre>
</div>
</div>
<p>The result is striking: only six distinct determinant values (±2, ±5, ±10), each occurring exactly four times — a <strong>perfectly uniform</strong> discrete distribution. Determinant zero is impossible, because no two-element partition of {1, 2, 3, 4} produces equal products. This uniformity is unique to the 2×2 case; it does not persist as the matrix grows.</p>
</section>
<section id="when-enumeration-isnt-an-option" class="level3">
<h3 class="anchored" data-anchor-id="when-enumeration-isnt-an-option">4×4: When Enumeration Isn’t an Option</h3>
<p>The natural next question is whether any of this generalizes: what happens with 4×4 matrices built from the digits 1 through 16, each used once? The honest answer is that the <em>method</em> from the 3×3 case doesn’t survive the jump: exhaustive enumeration is no longer feasible. This turns out to be more interesting than a simple “bigger version of the same result.”</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">factorial</span>(<span class="dv">16</span>) <span class="sc">|&gt;</span> <span class="fu">format</span>(<span class="at">scientific =</span> <span class="cn">FALSE</span>, <span class="at">big.mark =</span> <span class="st">","</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "20,922,789,888,000"</code></pre>
</div>
</div>
<p>That’s 20.92 trillions! Even at, say, 100 million determinants per second, enumerating every 4×4 filling would take on the order of two days of pure computation, and storing the results is its own problem. The 3×3 case worked because <span class="math inline">\(9!\)</span> fits comfortably in memory; the 4×4 case forces a change of approach—Monte Carlo sampling for the overall shape, and combinatorial optimization for the extremes, which is a genuinely different technique from anything used above.</p>
</section>
<section id="monte-carlo-approximation-of-the-shape" class="level3">
<h3 class="anchored" data-anchor-id="monte-carlo-approximation-of-the-shape">Monte Carlo approximation of the shape</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>det_mat_n <span class="ot">&lt;-</span> <span class="cf">function</span>(v, n) <span class="fu">det</span>(<span class="fu">matrix</span>(v, <span class="at">nrow =</span> n, <span class="at">ncol =</span> n, <span class="at">byrow =</span> <span class="cn">TRUE</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>B4 <span class="ot">&lt;-</span> <span class="dv">2000000</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>determinants_4x4 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B4, <span class="fu">det_mat_n</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>, <span class="dv">16</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>), <span class="dv">4</span>))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">N        =</span> B4,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Min      =</span> <span class="fu">min</span>(determinants_4x4),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Max      =</span> <span class="fu">max</span>(determinants_4x4),</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mean     =</span> <span class="fu">round</span>(<span class="fu">mean</span>(determinants_4x4), <span class="dv">2</span>),</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">SD       =</span> <span class="fu">round</span>(<span class="fu">sd</span>(determinants_4x4), <span class="dv">2</span>),</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Skewness =</span> <span class="fu">round</span>(<span class="fu">skewness</span>(determinants_4x4), <span class="dv">4</span>),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">Kurtosis =</span> <span class="fu">round</span>(<span class="fu">kurtosis</span>(determinants_4x4), <span class="dv">4</span>),</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Zero %</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">mean</span>(determinants_4x4 <span class="sc">==</span> <span class="dv">0</span>), <span class="dv">4</span>),</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        N    Min   Max Mean      SD Skewness Kurtosis Zero %
1 2000000 -38185 38304  5.5 8467.51  -0.0018    3.754 0.0101</code></pre>
</div>
</div>
<p>The symmetry argument from the 3×3 case carries over unchanged—swapping two rows still negates the determinant while preserving the permutation constraint, so the 4×4 distribution is exactly symmetric about zero too (skewness <span class="math inline">\(\approx 0\)</span> above, up to Monte Carlo noise).</p>
</section>
<section id="a-surprise-more-terms-but-less-gaussian" class="level3">
<h3 class="anchored" data-anchor-id="a-surprise-more-terms-but-less-gaussian">A surprise: more terms, but <em>less</em> Gaussian</h3>
<p>The Leibniz expansion of a 4×4 determinant has <span class="math inline">\(4! = 24\)</span> signed terms (12 positive, 12 negative) instead of 6. The naive CLT-flavored intuition is that more terms should push the distribution closer to Gaussian. The opposite happens: the 3×3 exact distribution has kurtosis 2.67 (flatter than normal, consistent with the tent/triangular shape described above), while the 4×4 Monte Carlo distribution has kurtosis 3.75—<em>heavier</em>-tailed than the normal distribution (kurtosis 3), not lighter.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df_shape <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">z =</span> determinants_exact <span class="sc">/</span> <span class="fu">sd</span>(determinants_exact), <span class="at">n =</span> <span class="st">"3x3 (exact, 9! perms)"</span>),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">z =</span> determinants_4x4   <span class="sc">/</span> <span class="fu">sd</span>(determinants_4x4),   <span class="at">n =</span> <span class="st">"4x4 (Monte Carlo, B=2e6)"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_shape, <span class="fu">aes</span>(<span class="at">x =</span> z, <span class="at">color =</span> n)) <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">linewidth =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">color =</span> <span class="st">"grey40"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#3498db"</span>, <span class="st">"#e74c3c"</span>)) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Standardized determinant distributions: 3×3 vs 4×4"</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Dashed grey curve is the standard normal, for reference"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Determinant / SD"</span>, <span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">color =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/plot-4x4-compare-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>A plausible explanation: each Leibniz term is a <em>product</em> of four correlated permutation entries rather than three. Products of correlated, bounded random variables tend to develop heavier tails than sums do—the CLT’s “more terms → more Gaussian” intuition applies to sums of <em>independent</em> terms, and neither independence nor pure summation holds here. Whether this trend continues (5×5, 6×6, …) is an open question worth checking computationally before claiming anything more general.</p>
<!-- TODO: worth running 5x5 (25 entries) via the same Monte Carlo approach to see if kurtosis keeps rising, or peaks and comes back down. Also worth trying to isolate the marginal distribution of a single Leibniz term (a product of 4 entries) to see directly why it's heavier-tailed than the 3-term product case. -->
</section>
<section id="finding-the-true-extremes-sampling-isnt-enough" class="level3">
<h3 class="anchored" data-anchor-id="finding-the-true-extremes-sampling-isnt-enough">Finding the true extremes: sampling isn’t enough</h3>
<p>The Monte Carlo sample above found a maximum determinant of 38304 out of 2 million draws. But random sampling estimates the <em>bulk</em> of a distribution well while systematically underselling its <em>extremes</em>—the rare permutations that produce very large determinants are, definitionally, rare, and 2 million out of <span class="math inline">\(2.09 \times 10^{13}\)</span> possibilities is a vanishingly small fraction (<span class="math inline">\(\sim 10^{-7}\)</span>).</p>
<p>To find the true maximum, we need search, not sampling. A simple multi-start hill climb—repeatedly swapping pairs of entries whenever the swap increases the determinant, from many random starting matrices—works well here:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>hill_climb <span class="ot">&lt;-</span> <span class="cf">function</span>(v, <span class="at">maximize =</span> <span class="cn">TRUE</span>) {</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  best_v <span class="ot">&lt;-</span> v</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  best_d <span class="ot">&lt;-</span> <span class="fu">det_mat_n</span>(v, <span class="dv">4</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  improved <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">while</span> (improved) {</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    improved <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>) {</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>      <span class="cf">for</span> (j <span class="cf">in</span> (i <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span><span class="dv">16</span>) {</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>        cand <span class="ot">&lt;-</span> best_v</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>        cand[<span class="fu">c</span>(i, j)] <span class="ot">&lt;-</span> cand[<span class="fu">c</span>(j, i)]</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>        d <span class="ot">&lt;-</span> <span class="fu">det_mat_n</span>(cand, <span class="dv">4</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> ((maximize <span class="sc">&amp;&amp;</span> d <span class="sc">&gt;</span> best_d) <span class="sc">||</span> (<span class="sc">!</span>maximize <span class="sc">&amp;&amp;</span> d <span class="sc">&lt;</span> best_d)) {</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>          best_v <span class="ot">&lt;-</span> cand</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>          best_d <span class="ot">&lt;-</span> d</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>          improved <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">v =</span> best_v, <span class="at">d =</span> best_d)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>n_starts <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>best_overall <span class="ot">&lt;-</span> <span class="sc">-</span><span class="cn">Inf</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>best_mat_vec <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>local_optima <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_starts)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (s <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_starts) {</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> <span class="fu">hill_climb</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>, <span class="dv">16</span>), <span class="at">maximize =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  local_optima[s] <span class="ot">&lt;-</span> res<span class="sc">$</span>d</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (res<span class="sc">$</span>d <span class="sc">&gt;</span> best_overall) {</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>    best_overall <span class="ot">&lt;-</span> res<span class="sc">$</span>d</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    best_mat_vec <span class="ot">&lt;-</span> res<span class="sc">$</span>v</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Best determinant found:"</span>, best_overall, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Best determinant found: 40800 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Starts reaching that exact value:"</span>, <span class="fu">sum</span>(local_optima <span class="sc">==</span> best_overall), <span class="st">"/"</span>, n_starts, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Starts reaching that exact value: 182 / 500 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">matrix</span>(best_mat_vec, <span class="at">nrow =</span> <span class="dv">4</span>, <span class="at">ncol =</span> <span class="dv">4</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4]
[1,]    7    3    8   16
[2,]   15    5   11    4
[3,]    2   12   13    6
[4,]   10   14    1    9</code></pre>
</div>
</div>
<p>Every one of the 500 random restarts converges to a local optimum no better than 40800, and over a third of them land on exactly that value—strong evidence this is the true global maximum, not just an artifact of one lucky start. That’s 6.5% above what 2 million random samples ever found.</p>
<p>Two independent checks reinforce this. First, expanding the neighborhood from pairwise swaps to 3-element cyclic swaps around the best matrix found no further improvement—so it’s not merely a strong 2-swap-only local optimum. Second, twenty independent runs of simulated annealing (which can escape local optima that hill climbing gets stuck in) all converged to the same value. Together, three independent search strategies agreeing this precisely is about as much confidence as a computational search can offer without a formal proof.</p>
<p>By the row-swap symmetry argument, the minimum (most negative) determinant is exactly $-$40800.</p>
</section>
<section id="uncharted-territory" class="level3">
<h3 class="anchored" data-anchor-id="uncharted-territory">Uncharted territory?</h3>
<p>A search of the <a href="https://oeis.org">OEIS</a> (On-Line Encyclopedia of Integer Sequences) and the maximal-determinant literature (Hadamard’s maximal determinant problem, D-optimal designs, and related work) turns up plenty of results for matrices restricted to <span class="math inline">\(\{0,1\}\)</span> or <span class="math inline">\(\{-1,+1\}\)</span> entries, but nothing for “the maximum determinant of an <span class="math inline">\(n \times n\)</span> matrix using each of <span class="math inline">\(1, \ldots, n^2\)</span> exactly once.” As far as I can tell, this specific problem—and the value 40800 for <span class="math inline">\(n=4\)</span>—isn’t recorded anywhere. It would be a fun rabbit hole to compute the <span class="math inline">\(n=5\)</span> case and consider submitting a sequence.</p>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>Examining how determinant distributions change with matrix size reveals a progression that is more varied than the “bigger version of the same” expectation.</p>
<p><strong>The 2×2 baseline</strong> is deceptively simple: permutations of {1, 2, 3, 4} into a 2×2 matrix yield only six possible determinant values (±2, ±5, ±10), each equally frequent, and singular matrices are impossible—no permutation of distinct digits produces a zero determinant.</p>
<p><strong>The 3×3 case</strong> is considerably richer: 362,880 permutations, many distinct values, and a distribution that is symmetric around zero but distinctly tent-shaped rather than Gaussian. The Monte Carlo approximation with a large random sample closely matches exact enumeration, validating sampling as a strategy for problems where exhaustive computation is infeasible.</p>
<p><strong>The 4×4 case</strong> shows that some properties scale and others do not. Symmetry around zero carries over—the row-swap argument is independent of matrix size. But the tent shape does not: rather than flattening toward Gaussian as the Leibniz expansion grows from 6 to 24 terms, the distribution becomes <em>more</em> leptokurtic (heavier-tailed, sharper-peaked). Each term is a product of correlated entries, not a sum of independent ones, so the Central Limit Theorem intuition doesn’t apply.</p>
<p>A secondary lesson is methodological: <strong>Monte Carlo finds the shape; combinatorial optimization finds the extremes.</strong> Two million random samples never reached the true 4×4 maximum. A multi-start hill climb did, converging reliably to a value that appears unrecorded in the existing literature.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>